Compatibility azurerm4
Azure/terraform-azurerm-avm-res-network-expressroutecircuit pull request #41
Opened 2024-10-13 11:32 UTC by adammontlake

## Description

## Type of Change

- [ ] Non-module change (e.g. CI/CD, documentation, etc.)
- [X] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates.
  - [X] Breaking changes.
  - [ ] Update to documentation

# Checklist

- [X] I'm sure there are no other open Pull Requests for the same update/change
- [X] My corresponding pipelines / checks run clean and green without any errors or warnings
- [X] I did run all  [pre-commit](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/terraform-contribution-flow/#5-run-pre-commit-checks) checks

2024-10-25 13:05 UTC, matt-FFFFFF requested changes

2024-10-25 13:05 UTC, matt-FFFFFF commented on terraform.tf
> +      version = ">= 4.4.0"
To avoid issues with azurerm v5 please can you change this to `~> 4.4`?

```suggestion
      version = "~> 4.4"
```

2024-10-25 13:05 UTC, matt-FFFFFF commented on examples/default/main.tf
> +      version = "> 4.0.0"
To avoid issues with azurerm v5 please can you change this to ~> 4.4?

```suggestion
      version = "~> 4.4"
```

2024-10-25 13:05 UTC, matt-FFFFFF commented on examples/complete-example/main.tf
> +      version = ">= 4.4.0"
To avoid issues with azurerm v5 please can you change this to ~> 4.4?

```suggestion
      version = "~> 4.4"
```

2024-10-25 13:05 UTC, matt-FFFFFF commented on examples/complete-example/README.md
> +      version = ">= 4.4.0"
To avoid issues with azurerm v5 please can you change this to ~> 4.4?

```suggestion
      version = "~> 4.4"
```

2025-02-06 05:14 UTC, khushal08 commented on examples/default/README.md
> +      version = "> 4.0.0"
One more

2025-02-06 08:32 UTC, matt-FFFFFF commented on README.md
> +- <a name="requirement_azurerm"></a> [azurerm](#requirement\_azurerm) (>= 4.4.0)
`~> 4.4`

2025-02-06 08:32 UTC, matt-FFFFFF commented on examples/complete-example/main.tf
> +      version = "~> 4.4"
This looks correct

2025-02-06 08:32 UTC, matt-FFFFFF commented on examples/default/README.md
> +      version = "> 4.0.0"
`~> 4.4`

2025-02-15 22:08 UTC, closed without merging